name: Run Python Script
on:
  push:
    branches:
      - main  # Adjust as needed for your workflow triggers

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: python redpinbar.py  # Replace 'script.py' with your actual script name
